### ISSUE TITLE
Asking for specific metric not supported.

### ISSUE THREAD

**Issue by mkuculyma** [intelsdi-x/snap-plugin-collector-schedstat#4]
**Snap version**:
snaptel version master-668a381

**Environment**:
- **OS** (e.g. from /etc/os-release):
Ubuntu 16.04.1 LTS
- **Kernel** 
4.4.0-45-generic 

**What happened**:
When asking for specific metric in task manifest: [task.txt](https://github.com/intelsdi-x/snap-plugin-collector-schedstat/files/624864/task.txt) 
The output of the task watch is root@developerka:/home/mkuculyma/snap/src/github.com/intelsdi-x/snap-plugin-collector-schedstat/examples/tasks# snaptel task watch cb5ff36b-8343-4ddd-85c1-a59facd3dda1
```
Watching Task (cb5ff36b-8343-4ddd-85c1-a59facd3dda1):
NAMESPACE 						 DATA 			 TIMESTAMP
^Cntel/proc/schedstat/cpu/cpu0/0/jiffiesWaiting 	 4.357092300771e+12 	 2016-12-01 15:23:54.408929792 +0100 CET
/intel/proc/schedstat/cpu/cpu1/0/jiffiesWaiting 	 3.358453627182e+12 	 2016-12-01 15:23:54.408931198 +0100 CET
/intel/proc/schedstat/cpu/cpu2/1/jiffiesWaiting 	 4.918068960057e+12 	 2016-12-01 15:23:54.408932428 +0100 CET
/intel/proc/schedstat/cpu/cpu3/1/jiffiesWaiting 	 4.739500929937e+12 	 2016-12-01 15:23:54.408933823 +0100 CET
/intel/proc/schedstat/cpu/cpu4/2/jiffiesWaiting 	 2.763918583286e+12 	 2016-12-01 15:23:54.408934507 +0100 CET
/intel/proc/schedstat/cpu/cpu5/2/jiffiesWaiting 	 2.631446709976e+12 	 2016-12-01 15:23:54.408936392 +0100 CET
/intel/proc/schedstat/cpu/cpu6/2/jiffiesWaiting 	 4.463907897758e+12 	 2016-12-01 15:23:54.408937066 +0100 CET
/intel/proc/schedstat/cpu/cpu7/2/jiffiesWaiting 	 2.609672864726e+12 	 2016-12-01 15:23:54.408937715 +0100 CET
Stopping task watch
```
**What you expected to happen**:
Only requested metric `/intel/proc/schedstat/cpu/cpu7/2/jiffiesWaiting`  should be reported:

**Steps to reproduce it** (as minimally and precisely as possible):

1. Start Snap
2. Load schedstat plugin 
3. Create task: [task.txt](https://github.com/intelsdi-x/snap-plugin-collector-schedstat/files/624883/task.txt)

**Comment by sandlbn** [comment]
@mkuculyma We don't need to have a support for specific core. Schedstat data is only interesting when you are looking at the distribution of the threads, per core and per socket. One metric will not tell you anything. I don't know if this is limitation. If is we can add info about this.

**Comment by mkuculyma** [comment]
@sandlbn ok, adding info should be sufficient in this case. And could it be possible to change the order of cpu_id and socket_id? For example: /intel/proc/schedstat/cpu/<socket_id>/<cpu_id>/jiffiesWaiting. This would be more intuitive.
